version: "3"
services:
  mysql:
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chore
      MYSQL_USER: chore
      MYSQL_PASSWORD: chore
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "choremysql:/var/lib/mysql"
    networks:
      - chore
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-pchore"]
      retries: 3
      timeout: 5s

networks:
  chore:
    driver: bridge

volumes:
    choremysql:
        driver: local